# Generated by Django 5.1.5 on 2025-10-10 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0002_alter_stock_symbol'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='purchase_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
